# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, /
# find the sum of the even-valued terms.

# Comments Section:
# - Straight forward algorithm.

def problem2():
    t0 = 1
    t1 = 2
    sum = 0
    while t1 <= 4000000:
        if t1 % 2 == 0:
            sum += t1
        t0, t1 = t1, t0 + t1
    return sum
        
        
