# How many distinct terms are in the sequence generated by a**b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

# Comments Section:
# - Straigh forward algorithm

def problem29():
    nums = set()
    for a in range(2,101):
        for b in range(2,101):
            nums.add(a**b)
    return len(nums)
